#if !defined(SPOKK_SHADER_INTERFACE_H)
#define SPOKK_SHADER_INTERFACE_H

#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_POSITION     0
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_NORMAL       1
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_TANGENT      2
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_BITANGENT    3
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_BONE_INDEX   4
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_BONE_WEIGHT  5
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_COLOR0       6
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_COLOR1       7
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_COLOR2       8
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_COLOR3       9
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_TEXCOORD0   10
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_TEXCOORD1   11
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_TEXCOORD2   12
#define SPOKK_VERTEX_ATTRIBUTE_LOCATION_TEXCOORD3   13

#endif  // defined(SPOKK_SHADER_INTERFACE_H)
