#version 450 core
#pragma shader_stage(compute)
layout(std140, binding=0) buffer InBuffer {
	ivec4 values[];
} innie;
layout(std140, binding=1) buffer OutBuffer {
	ivec4 values[];
} outie;
layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;
void main() {
	uint gid = gl_GlobalInvocationID.x;
	if (gid < uint(outie.values.length())) {
		outie.values[gid] = innie.values[gid] * 2;
	}
}